# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.4.0

    working_directory: ~/repo

    steps:
      - checkout

      # Debian doesn't consider LSB essential. Sigh.
      - run: sudo apt-get install lsb-release

      # From https://rethinkdb.com/docs/install/debian/
      - run: echo "deb http://download.rethinkdb.com/apt `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
      - run: wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
      - run: sudo apt-get update
      - run: sudo apt-get install rethinkdb

      # From https://www.rethinkdb.com/docs/start-on-startup/
      # (systemctl currently fails with 'Failed to get D-Bus connection: Unknown error -1')
      - run: sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
      - run: sudo /etc/init.d/rethinkdb start

      - run: node --version
      - run: npm --version
      - run: rethinkdb --version
      - run: pwd

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

